version: '3'

services:
  pia:
    image: colinhebert/pia-openvpn
    container_name: pia
    restart: always
    networks: 
      - web
    environment:
      - REGION=Switzerland
      - USERNAME=xxxxxx
      - PASSWORD=xxxxxx
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    dns:
      - 209.222.18.222
      - 209.222.18.218

  ip-default:
    image: tutum/curl
    container_name: ip-default
    restart: always
    networks: 
      - web

  ping:
    image: juamorous/ubuntu-ifconfig-ping
    container_name: ping
    restart: always
    networks: 
      - web
    
  pingvpn:
    image: juamorous/ubuntu-ifconfig-ping
    container_name: pingvpn
    restart: always
    networks: 
      - container:pia

  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    restart: always
    ports:
      - "6789:6789"
    networks:
      - container:pia
    environment:
      - PUID=${USER_ID}
      - PGID=${GROUP_ID}
    volumes:
      - ./media/nzbget/config:/config
      - ./media/nzbget/downloads:/downloads
    labels:
      - "traefik.enable=true"
      - "traefik.backend=nzbget"
      - "traefik.frontend.rule=Host:nzbget.${DOMAIN_NAME}"
      - "traefik.port=6789"
      - "traefik.docker.network=web"
    depends_on:
      - pia

  # hydra:
  #   image: linuxserver/hydra
  #   container_name: hydra
  #   restart: always
  #   ports:
  #     - "5075:5075"
  #   networks:
  #     - container:pia
  #   environment:
  #     - PUID=${USER_ID}
  #     - PGID=${GROUP_ID}
  #   volumes:
  #     - ./media/hydra/config:/config
  #     - ./media/hydra/downloads:/downloads
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=hydra"
  #     - "traefik.frontend.rule=Host:hydra.${DOMAIN_NAME}"
  #     - "traefik.port=5075"
  #     - "traefik.docker.network=web"
  #   depends_on:
  #     - pia
  #     - nzbget

  # sonarr:
  #   image: linuxserver/sonarr:latest
  #   container_name: sonarr
  #   restart: always
  #   networks:
  #     - container:pia
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /dev/rtc:/dev/rtc:ro
  #     - ./media/sonarr/series:/tv
  #     - ./media/sonarr/config:/config
  #     - ./media/transmission/downloads/:/downloads
  #   environment:
  #     - PUID=${USER_ID}
  #     - PGID=${GROUP_ID}
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=sonarr"
  #     - "traefik.frontend.rule=Host:sonarr.${DOMAIN_NAME}"
  #     - "traefik.port=8989"
  #     - "traefik.docker.network=web"
  #   depends_on:
  #     - pia
  #     - nzbget
  #     - hydra

  # radarr:
  #   image: linuxserver/radarr:latest
  #   container_name: radarr
  #   restart: always
  #   networks:
  #     - container:pia
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /dev/rtc:/dev/rtc:ro
  #     - ./media/radarr/movies:/movies
  #     - ./media/radarr/config:/config
  #     - ./media/transmission/downloads/:/downloads
  #   environment:
  #     - PUID=${USER_ID}
  #     - PGID=${GROUP_ID}
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=radarr"
  #     - "traefik.frontend.rule=Host:radarr.${DOMAIN_NAME}"
  #     - "traefik.port=7878"
  #     - "traefik.docker.network=web"
  #   depends_on:
  #     - pia
  #     - nzbget
  #     - hydra

  # ombi:
  #   image: linuxserver/ombi
  #   container_name: ombi
  #   restart: always
  #   ports:
  #     - "3579:3579"
  #   networks:
  #     - container:pia
  #   environment:
  #     - PUID=${USER_ID}
  #     - PGID=${GROUP_ID}
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - ./media/ombi/config:/config
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=ombi"
  #     - "traefik.frontend.rule=Host:ombi.${DOMAIN_NAME}"
  #     - "traefik.port=3579"
  #     - "traefik.docker.network=web"
  #   depends_on:
  #     -pia

networks:
  web:
    external:
      name: traefik